FROM mysql:8

USER root

ADD ./my.cnf /etc/mysql/conf.d/
ADD ./init /docker-entrypoint-initdb.d

EXPOSE 3306

CMD ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
